name: minder
description: Minder Mobile

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info_plus: ^3.0.2
  http: ^0.13.5
  either_dart: ^0.3.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^6.1.0
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.0
  focused_menu: ^1.0.5
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.11.0
  get_it: ^7.2.0
  pin_code_fields: ^7.4.0
  shimmer: ^2.0.0
  tiengviet: ^0.5.0
  calendar_date_picker2: ^0.5.2
  signalr_netcore: ^1.3.3
  emoji_picker_flutter: ^1.5.4
  image_picker: ^0.8.7+4
  image_cropper: ^4.0.1
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_typeahead: ^4.3.8
  flutter_google_places: ^0.3.0
  photo_manager: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/common/
    - assets/images/logo/
    - assets/images/background/
    - assets/images/setting/
    - assets/icons/
    - assets/map_style/map_style.txt

  fonts:
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

flutter_intl:
  enabled: true
  generate: true
